"""initial schema

Revision ID: 6cdb30f83550
Revises: 
Create Date: 2026-04-19 11:02:52.977599

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6cdb30f83550'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_cycle_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('personal','professional')", name='ck_cycles_category'),
    sa.ForeignKeyConstraint(['next_cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cycles_user_cat_ended', 'cycles', ['user_id', 'category', 'ended_at'], unique=False)
    op.create_index('ix_cycles_user_cat_started', 'cycles', ['user_id', 'category', 'started_at'], unique=False)
    op.create_index('uq_cycles_user_cat_active', 'cycles', ['user_id', 'category'], unique=True, postgresql_where='ended_at IS NULL')
    op.create_table('display_id_sequences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persistent_task_id', sa.UUID(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('previous_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open','completed','canceled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'display_id', name='uq_tasks_user_display_id')
    )
    op.create_index('ix_tasks_cycle_filter', 'tasks', ['cycle_id', 'deleted_at', 'status', 'position'], unique=False)
    op.create_index('ix_tasks_lineage', 'tasks', ['user_id', 'persistent_task_id'], unique=False)
    op.create_index('ix_tasks_previous', 'tasks', ['previous_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_previous', table_name='tasks')
    op.drop_index('ix_tasks_lineage', table_name='tasks')
    op.drop_index('ix_tasks_cycle_filter', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('display_id_sequences')
    op.drop_index('uq_cycles_user_cat_active', table_name='cycles', postgresql_where='ended_at IS NULL')
    op.drop_index('ix_cycles_user_cat_started', table_name='cycles')
    op.drop_index('ix_cycles_user_cat_ended', table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
